#!/bin/bash

exec 2>&1

if [[ ! -f /etc/services ]]; then
  cp -v {{pkgPathFor "core/iana-etc"}}/etc/services /etc/services
fi

cp {{pkg.svc_config_path}}/client.json {{pkg.svc_data_path}}/config

alias tc="tezos-client -base-dir {{pkg.svc_data_path}}"

tc bootstrapped

if [[ "{{cfg.wallet_secret_key}}" != "" && "{{cfg.wallet_public_key}}" != "" ]]; then
  tc forget all keys -force true
  tc add public key "endorser" "{{cfg.wallet_public_key}}"
  tc add secret key "endorser" "{{cfg.wallet_secret_key}}"
else
  tc gen keys "endorser"
fi
