#!/bin/bash

exec 2>&1

cp {{pkg.svc_config_path}}/client.json {{pkg.svc_data_path}}/config

exec tezos-client -base-dir {{pkg.svc_data_path}} \
  launch daemon -endorsement \
  | tee {{pkg.svc_data_path}}/endorser.log
