version: '3'

services:
  node:
    container_name: node
    ports:
    - 9733:9733
    - 8733:8733
    volumes:
    - ./tezos-node:/conf
    - data:/hab/svc/tezos-node/data
    image: misthosio/tezos-node
    privileged: true
    command: "start misthosio/tezos-node --config-from /conf"
    environment:
      HAB_TEZOS_NODE: |
        net_port=9733
        rpc_port=8733
        rpc_listen_addr="0.0.0.0"

  baker:
    container_name: baker
    image: misthosio/tezos-baker
    command: "start misthosio/tezos-baker --peer node --bind node:tezos-node.default --config-from /conf"
    volumes:
    - ./tezos-baker:/conf
    environment:
      HAB_TEZOS_BAKER: |
        wallet_secret_key="${BAKER_SECRET_KEY}"
        wallet_public_key="${BAKER_PUBLIC_KEY}"
    links:
    - node

volumes:
  data: {}
