version: '3'

services:
  node:
    container_name: node
    ports:
    - 9733:9733
    - 8733:8733
    volumes:
    - data:/hab/svc/tezos-node/data
    image: misthosio/tezos-node
    privileged: true
    command: "start misthosio/tezos-node"
    environment:
      HAB_TEZOS_NODE: |
        net_port=9733
        rpc_port=8733
        rpc_listen_addr="0.0.0.0"

  baker:
    container_name: baker
    image: misthosio/tezos-baker
    command: "start misthosio/tezos-baker --peer node --bind node:tezos-node.default"
    environment:
      HAB_TEZOS_BAKER: |
        wallet_secret_key="${DELEGATE_SECRET_KEY}"
        wallet_public_key="${DELEGATE_PUBLIC_KEY}"
    links:
    - node

  endorser:
    container_name: endorser
    image: misthosio/tezos-endorser
    command: "start misthosio/tezos-endorser --peer node --bind node:tezos-node.default"
    environment:
      HAB_TEZOS_ENDORSER: |
        wallet_secret_key="${DELEGATE_SECRET_KEY}"
        wallet_public_key="${DELEGATE_PUBLIC_KEY}"
    links:
    - node

volumes:
  data: {}
