#!/bin/bash

exec 2>&1

if [[ ! -f /etc/services ]]; then
  cp -v {{pkgPathFor "core/iana-etc"}}/etc/services /etc/services
fi

cp {{pkg.svc_config_path}}/client.json {{pkg.svc_data_path}}/config

alias tc="tezos-client -base-dir {{pkg.svc_data_path}}"

tc bootstrapped

if [[ "{{cfg.wallet_secret_key}}" != "" && "{{cfg.wallet_public_key}}" != "" ]]; then
  tc add public key "baker" "{{cfg.wallet_public_key}}"
  tc add secret key "baker" "{{cfg.wallet_secret_key}}"
else
  tc gen keys "baker"
fi

# tc forget contract "my_account" >/dev/null 2>&1 || true
# tc originate free account "my_account" for "my_identity"

# if ! tc get balance for "my_identity" >/dev/null 2>&1 ; then
#   echo "Generating new manager key (known as 'my_identity')..."
#   $client gen keys "my_identity"
# fi
# if ! $client get balance for "my_account" >/dev/null 2>&1 ; then
#   echo "Creating new account for 'my_identity' (known as 'my_account')..."
#   $client forget contract "my_account" >/dev/null 2>&1 || true
#   $client originate free account "my_account" for "my_identity"
# fi
